{% set name = "prometheus_client" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e0ced7fbbd40f7b84962d5d2ab6f17ef88a72504dcf7c0b40737b43b2a461f9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.openmetrics
    - prometheus_client.twisted
  commands:
    - pip check
    - pytest tests -v --ignore=tests/test_multiprocess.py   # [win]
    - pytest tests -v                                       # [not win]
  requires:
    - pip
    - pytest
    - twisted
    - asgiref
    - pytest-benchmark

about:
  home: https://github.com/prometheus/client_python
  summary: Python client for the Prometheus monitoring system.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/prometheus/client_python
  doc_url: https://github.com/prometheus/client_python#readme
  description: The official Python client for Prometheus.

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
