{% set name = "prometheus_client" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 252505a722ac04b0456be05c05f75f45d760c2911ffc45f2a06bcaed9f3ae3fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.openmetrics
    - prometheus_client.twisted
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - twisted

about:
  home: https://github.com/prometheus/client_python
  summary: Python client for the Prometheus monitoring system.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/prometheus/client_python
  doc_url: https://github.com/prometheus/client_python#readme
  description: The official Python client for Prometheus.

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
