{% set name = "prometheus_client" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: 4541efd404e34d56303ba9539a41ba3b378c1ab309a2866aafc7a3a26b5589ae

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.openmetrics
    - prometheus_client.twisted
  commands:
    - pip check
  requires:
    - pip
    - python
    - twisted

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for the Prometheus monitoring system
  dev_url: https://github.com/prometheus/client_python
  doc_url: https://github.com/prometheus/client_python#readme

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
