{% set name = "prometheus_client" %}
{% set version = "0.0.21" %}
{% set build = 0 %}
{% set sha256 = "0013d1ef25700dbfa2ea0c4fe799dd1fd72702d109467fd09a2eafa2d7e8f7e6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/prometheus/client_python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - twisted

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.twisted

about:
  home: https://github.com/prometheus/client_python
  license: Apache 2.0
  summary: 'Python client for the Prometheus monitoring system.'
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
