{% set version = "0.13.0" %}

package:
  name: prometheus_client
  version: {{ version }}

source:
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: 65124dce0acc17907f6ae86d64cc18e404640ae08e7a795b20fcbc13eb2b0c2f

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.openmetrics
    - prometheus_client.twisted
  commands:
    - pip check
  requires:
    - pip
    - python <3.10
    - twisted

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for the Prometheus monitoring system 
  dev_url: https://github.com/prometheus/client_python
  doc_url: https://github.com/prometheus/client_python#readme

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
