travis:
  secure:
    BINSTAR_TOKEN: P886enx2ksc9BItPjzfUWY2vnhElbkCKPiQyyNXCnngrlxpCbLCR3TRDuNv+uhu43brqWPy5ZcIYwsndWuVHzXu6/GszyFwar9ZJ9MGgLv5kj6YAOTjjTxKnF+K19IEJMuXQp1g4ZN8yDzzq/DSXSHTUUGX9HOfA7dzX2mGqDdW7Dz7whG/cvor3RFkqQxRL02MxtxWko81A9g0bqcsFlKys/6mTUx3mKnNpjLl+SD2pbnQYbK/drdLAVgKzAZBmrnvfez/YFpQi4OIwYsSUZnyGPz2OFTDuaopMo20Klvz/i3y6Jr5EqAlvFQkYTQ2TuXEwfJDR31EcnZKDsehFT/h8XhcFPp3LkTbw0RoTrpmJln5qcqlmvRXKLViKdWW7fmoluUCry14i7PTCMOM18fHY+yOB+Gb7rXAlEAKJe4LR9AR02SGYp03z1iPMfc+wYB1TbzwAGcsx7eRQcDJD7VHYFppkYnV3yv+RmlwQIsNLh8j5q5RmKyBLBalwVg8SPWGKHfJXUc1N39Ar5lN9IoID0hyuvc2Xotg8PF1EglKmogy8zmTNLJxfICwU+qD0GWaDwwliOSI96iRARTpWxoyOGYINyszg/sN5wuaSW1xJoMhPTiVrS1oVp1gWcagSPp+3LkJ3S1FXZMGI3sEbXiV2bJ+Ernd5T10kAoQzLuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
